FROM node:lts-alpine

# Create destination directory
RUN mkdir -p /usr/src/tickets-admin
WORKDIR /usr/src/tickets-admin
COPY ./ .
COPY ./start-reload.sh /start-reload.sh

RUN yarn install

# Expose 3000 on container
EXPOSE 3000